
But de l'exercice : Comprendre le percepton par un exemple le plus simple possible.

1 seul preceptron 
4 entrées de type 0/1
1 seule sortie de type 0/1


Apprendre à reconnaitre les deux motifs suivants : 1,0,0,0 => 1 et 0,0,1,0 => 0


In [9]:
import math 
import numpy as np
 
# our sigmoid function, tanh is a little nicer than the standard 1/(1+e^-x)
def sigmoid(x):
    return np.tanh(x)

poids = np.random.rand(4)

print(poids)
ap = 0.01

[ 0.58641796  0.23996159  0.33738628  0.25291259]


In [10]:
def perceptron(e1, e2, e3, e4):
    somme = e1 * poids[0] + e2 * poids[1] + e3 * poids[2] + e4 * poids[3]
    
    return sigmoid(somme)

print(perceptron(10, 0, 0, 0))

0.999983876297


In [16]:
def train(e1, e2, e3, e4, r):
    p = perceptron(e1, e2, e3, e4)
    e = r-p
    poids[0]= poids[0] + e*ap*e1
    poids[1]= poids[1] + e*ap*e2
    poids[2]= poids[2] + e*ap*e3
    poids[3]= poids[3] + e*ap*e4
    return (p,e)
    
print(poids)
for i in range(10000):
    train(1,0,0,0,1)
    train(0,0,1,0,0)

print(poids)
print(perceptron(1,0,0,0))
print(perceptron(0,0,1,0))


[ 0.67928595  0.33282957  0.43025426  0.34578057]
[  2.99491601e+00   3.32829573e-01   9.98127610e-45   3.45780570e-01]
0.995004340214
9.98127609952e-45
